clear all;
close all;
clc;

hfig = figure();

h_device_button = uicontrol(hfig,...
                'style', 'pushbutton',...
                'units', 'normalized',...
                'position', [0.5, 0.9, 0.2, 0.05],...
                'string', 'find device',...
                'callback', @device_finder);
            
h_start_button = uicontrol(hfig,...
                'style', 'pushbutton',...
                'units', 'normalized',...
                'position', [0.75, 0.8, 0.2, 0.05],...
                'string', 'start audio',...
                'callback', @start_audio);

h_device_popup = uicontrol(hfig,...
                'style', 'popup',...
                'tag', 'dev_popup',...
                'string', 'no device available',...
                'units', 'normalized',...
                'position', [0.75, 0.9, 0.2, 0.05]);
            
h_polar_plot = plot(0, 0,...
                    'tag','plot');

%view([90 -90]); %polarplot umdrehen, dass 0° oben stehen
global deg;

deg = 0;

set(gca(), 'buttondownfcn', @dir_change_fcn);

guidata(hfig, guihandles(hfig));