clear all;
close all;
clc;

background = [1 1 0.7];
background_user = [1 1 0.8];
lautsprecher = imread('lautsprecher','png');
%degree_symbol = sprintf('%c', char(176));

%--------------------------------------------------------------------------
hfig = figure();

set(hfig,'units','normalized',...
         'tag','mainfig',...
         'name', 'HRTF-Test',...
         'position', [0.05 0.05 0.9 0.9],...
         'ToolBar','none',...
         'Color',[background],...
         'MenuBar','none');
     
%-------Azimuth------------------------------------------------------------

title_Azimuth = uicontrol(hfig,'style','text',...
                                'units', 'normalized',...
                                'position',   [0.05 0.76 0.1 0.04],...
                                'string', 'Azimuth:',...
                                'FontUnits','normalized',...
                                'FontSize',0.9,...
                                'BackgroundColor', [background]);
                            
h_azdir_edit = uicontrol(hfig,...
                        'style', 'edit',...
                        'tag', 'azdir_edit',...
                        'units', 'normalized',...
                        'position', [0.18, 0.76, 0.1, 0.05],...
                        'BackgroundColor', [background_user],...
                        'FontUnits','normalized',...
                        'Fontsize', 0.5,...
                        'string', '0');
            
azi_panel = uipanel('Parent',hfig,...
                     'units', 'normalized',...
                     'tag', 'azi_panel',...
                     'BackgroundColor',[1 1 1],...
                     'Position', [0.05 0.05 0.55 0.7]);
                     
azi_axes = axes('Parent', azi_panel,...
                'Units','normalized',...
                'tag', 'azi_axes',...
                'Box','Off',...
                'XLim', [-1 1],...
                'YLim', [-1 1],...
                'Position', [0 0 1 1]); 
                axis off
                
azi_picture_panel = uipanel('Parent',azi_panel,...
                 'units', 'normalized',...
                 'BackgroundColor', 'w',...
                 'ShadowColor', 'w',...
                 'tag', 'azi_picture_panel',...
                 'Position', [0.46 0.86 0.08 0.08]);
             
azi_picture = axes('Parent', azi_picture_panel,...
                'Units','normalized',...
                'Box','Off',...
                'Position',[0 0 1 1]);       
                axis(azi_picture);
                image(lautsprecher);
                axis image  
                axis off
               
%--------------Elevation---------------------------------------------------

title_Elevation = uicontrol(hfig,'style','text',...
                            'units', 'normalized',...
                            'position',   [0.7 0.76 0.1 0.04],...
                            'string', 'Elevation:',...
                            'FontUnits','normalized',...
                            'FontSize',0.9,...
                            'BackgroundColor', [background]);

h_eldir_edit = uicontrol(hfig,...
                'style', 'edit',...
                'tag', 'eldir_edit',...
                'units', 'normalized',...
                'position', [0.82, 0.76, 0.1, 0.05],...
                'BackgroundColor', [background_user],...
                'FontUnits','normalized',...
                'Fontsize', 0.5,...
                'string', '0');
                
elev_panel = uipanel('Parent',hfig,...
                 'units', 'normalized',...
                 'BackgroundColor', 'w',...
                 'tag', 'elev_panel',...
                 'Position', [0.7 0.05 0.25 0.7]);
                     
elev_axes = axes('Parent', elev_panel,...
                'Units','normalized',...
                'tag', 'elev_axes',...
                'Box','Off',...
                'XLim', [-1 1],...
                'YLim', [-180 180],...
                'Position', [0 0 1 1]); 
                axis off
                
elev_picture_panel = uipanel('Parent',elev_panel,...
                 'units', 'normalized',...
                 'BackgroundColor', 'w',...
                 'ShadowColor', 'w',...
                 'tag', 'elev_picture_panel',...
                 'Position', [0.45 0.8 0.1 0.1]);
             
elev_picture = axes('Parent', elev_picture_panel,...
                'Units','normalized',...
                'Box','Off',...
                'Position',[0 0 1 1]);       
                axis(elev_picture);
                image(lautsprecher);
                axis image  
                axis off
                

%--------------------------------------------------------------------------

h_device_button = uicontrol(hfig,...
                'style', 'pushbutton',...
                'units', 'normalized',...
                'position', [0.05, 0.9, 0.15, 0.05],...
                'FontUnits','normalized',...
                'Fontsize', 0.5,...
                'string', 'find device:',...
                'BackgroundColor', [background_user],...
                'callback', @device_finder);
            
h_device_popup = uicontrol(hfig,...
                'style', 'popup',...
                'tag', 'dev_popup',...
                'FontUnits','normalized',...
                'Fontsize', 0.3,...
                'string', 'no device available',...
                'units', 'normalized',...
                'BackgroundColor', [background_user],...
                'position', [0.05, 0.83, 0.15, 0.05]);
            
h_start_button = uicontrol(hfig,...
                'style', 'pushbutton',...
                'units', 'normalized',...
                'position', [0.5, 0.85, 0.15, 0.05],...
                'FontUnits','normalized',...
                'Fontsize', 0.5,...
                'string', 'start audio',...
                'BackgroundColor', [background_user],...
                'callback', @start_audio);   
            
%--------------------------------------------------------------------------
          
set(azi_panel, 'buttondownfcn', @azdir_change);
set(elev_panel, 'buttondownfcn', @eldir_change);

guidata(hfig, guihandles(hfig));