% HRTF_GUI Hauptskript zum Probehören von HRTFs verschiedener Tonquellen

%   Skript erstellt Benutzeroberfläche mit Optionen zur Auswahl der
%   Output-Devices und Tonquellen, sowie Auswahl der gewünschter Azimuth- 
%   und Elevation-Winkel in Echtzeit
%   
% Copyright 2014 Laura Hartog, Franz Wichert

clear all;
close all;
clc;

% Festlegen der Farbgestaltung
background = [1 1 0.7];
background_user = [1 1 0.8];

% Einlesen der Bilder der Polarplots und der Lautsprechersymbole
azi_lautsprecher = imread('azi_lautsprecher','png');
elev_lautsprecher = imread('elev_lautsprecher','png');
Polar = imread('Polar','png');
elev_polar = imread('elev_polar','png');

%---------Erstellen der GUI------------------------------------------------

hfig = figure();
set(hfig,'units','normalized',...
         'tag','mainfig',...
         'name', 'HRTF-Test',...
         'position', [0.05 0.05 0.9 0.9],...
         'ToolBar','none',...
         'Color',[background],...
         'resize', 'off',...
         'MenuBar','none');

                            
%%%%%%%%%%% Azimuth %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

title_Azimuth = uicontrol(hfig,'style','text',...
                        'units', 'normalized',...
                        'position',   [0.05 0.76 0.1 0.04],...
                        'string', 'Azimuth:',...
                        'FontUnits','normalized',...
                        'FontSize',0.9,...
                        'BackgroundColor', [background]);
                    
% Erstellen des edit Fensters zur Anzeige der Winkel mit Startwert 0°                            
h_azdir_edit = uicontrol(hfig,...
                        'style', 'edit',...
                        'tag', 'azdir_edit',...
                        'units', 'normalized',...
                        'position', [0.18, 0.76, 0.1, 0.05],...
                        'BackgroundColor', [background_user],...
                        'FontUnits','normalized',...
                        'Fontsize', 0.5,...
                        'string', '0');
                    
% Panel der Oberfläche zum Festlegen der Azimuth Winkel            
azi_panel = uipanel('Parent',hfig,...
                     'units', 'normalized',...
                     'tag', 'azi_panel',...
                     'BackgroundColor',[1 1 1],...
                     'Position', [0.05 0.05 0.45 0.7]);
                 
% Aufspannen der Achen in azi_panel zum registrieren der gewählten Koordinaten                        
azi_axes = axes('Parent', azi_panel,...
                'Units','normalized',...
                'tag', 'azi_axes',...
                'Box','Off',...
                'XLim', [-1 1],... % Festelgen der Achsen zur Bestimmung der
                'YLim', [-1 1],... % Koordinaten
                'Position', [0 0 1 1]);
                axis off
                
% Panel für das Polarkreuz im Hintergrund
background_picture_panel = uipanel('Parent',azi_panel,...
                 'units', 'normalized',...
                 'BackgroundColor', 'w',...
                 'ShadowColor', 'w',...
                 'tag', 'background_picture_panel',...
                 'HitTest','off',...     % Panel nicht von Bedeutung - Klicks werden         
                 'Position', [0 0 1 1]); % weiterhin in azi-axes registriert
             
% Aufspannen der Axen und Laden des Hintergrundbildes als Polarkreuz
background_picture = axes('Parent', background_picture_panel,...
                'Units','normalized',...
                'Box','Off',...
                'Position',[0 0 1 1]); 
                axis(background_picture);
                image(Polar,...
                    'HitTest','off');
                axis image  
                axis off
% Erstellen eines Panels zur Positinierung des Lautsprechersymbols               
azi_picture_panel = uipanel('Parent',azi_panel,...
                 'units', 'normalized',...
                 'BackgroundColor', 'w',...
                 'ShadowColor', 'w',...
                 'tag', 'azi_picture_panel',... % Tag zur Nutzung in nach-
                 'Position', [0.46 0.803 0.08 0.08]); % folgenden Funktionen
             
% Aufspannen von Achsen in azi_picture_panel und Ausfüllen mit Lautsprechersymbol         
azi_picture = axes('Parent', azi_picture_panel,...
                'Units','normalized',...
                'Box','Off',...
                'Position',[0 0 1 1]);       
                axis(azi_picture);
                image(azi_lautsprecher);
                axis image  
                axis off
               
%%%%%%%%%%%%%%%% Elevation %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Wiederholen des Azimuth-Vorgangs für Elevation

title_Elevation = uicontrol(hfig,'style','text',...
                            'units', 'normalized',...
                            'position',   [0.7 0.76 0.1 0.04],...
                            'string', 'Elevation:',...
                            'FontUnits','normalized',...
                            'FontSize',0.9,...
                            'BackgroundColor', [background]);

h_eldir_edit = uicontrol(hfig,...
                'style', 'edit',...
                'tag', 'eldir_edit',...
                'units', 'normalized',...
                'position', [0.82, 0.76, 0.1, 0.05],...
                'BackgroundColor', [background_user],...
                'FontUnits','normalized',...
                'Fontsize', 0.5,...
                'string', '0');
                
elev_panel = uipanel('Parent',hfig,...
                 'units', 'normalized',...
                 'BackgroundColor', 'w',...
                 'tag', 'elev_panel',...
                 'Position', [0.03+0.45+0.04 0.05 0.45 0.7]);
                     
elev_axes = axes('Parent', elev_panel,...
                'Units','normalized',...
                'tag', 'elev_axes',...
                'Box','Off',...
                'XLim', [-1 1],...
                'YLim', [-1 1],...
                'Position', [0 0 1 1]); 
                axis off
                

elev_background_picture_panel = uipanel('Parent',elev_panel,...
                 'units', 'normalized',...
                 'BackgroundColor', 'w',...
                 'ShadowColor', 'w',...
                 'tag', 'background_picture_panel',...
                 'HitTest','off',...
                 'Position', [0 0 1 1]);

elev_background_picture = axes('Parent', elev_background_picture_panel,...
                'Units','normalized',...
                'Box','Off',...
                'Position',[0 0 1 1],...
                'tag', 'head_picture'); 
                axis(elev_background_picture);
                image(elev_polar,...
                    'HitTest','off');
                axis image  
                axis off
                
elev_picture_panel = uipanel('Parent',elev_panel,...
                 'units', 'normalized',...
                 'BackgroundColor', 'w',...
                 'ShadowColor', 'w',...
                 'tag', 'elev_picture_panel',...
                 'Position', [0.174 0.465 0.08 0.08]);
             
elev_picture = axes('Parent', elev_picture_panel,...
                'Units','normalized',...
                'Box','Off',...
                'Position',[0 0 1 1]);       
                axis(elev_picture);
                image(elev_lautsprecher);
                axis image  
                axis off
                

%%%%%%%%%%%%%%%%%%%%%%%%% Buttons %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Erstellen des popup menu zur Auswahl der Tonquelle
sound_popup = uicontrol(hfig, 'style', 'popupmenu',...
                                'tag', 'sound_popup',...
                                'units', 'normalized',...
                                'position',   [0.8 0.85 0.18 0.04],...
                                'string', {'evil_laugh.wav','evil_kids.wav',...
                                'evil_dog.wav','fly.wav','mosquito.wav','seagull.wav'},...
                                'FontUnits','normalized',...
                                'FontSize',0.6,...
                                'BackgroundColor', [background_user]);
                            
% Pushbutton zum Aufruf der Funktion device_finder                           
h_device_button = uicontrol(hfig,...
                'style', 'pushbutton',...
                'units', 'normalized',...
                'position', [0.05, 0.9, 0.15, 0.05],...
                'FontUnits','normalized',...
                'Fontsize', 0.5,...
                'string', 'find device:',...
                'BackgroundColor', [background_user],...
                'callback', @device_finder);
            
% Popup Fenster mit Auswahl der In- und Output Devices           
h_device_popup = uicontrol(hfig,...
                'style', 'popup',...
                'tag', 'dev_popup',...
                'FontUnits','normalized',...
                'Fontsize', 0.3,...
                'string', 'no device available',... %Kommentar falls Button find device
                'units', 'normalized',...           % noch nicht betätigt
                'BackgroundColor', [background_user],...
                'position', [0.05, 0.83, 0.15, 0.05]);
            
% Pushbutton führt Funktion 'start_audio' aus, die Tonquelle wird abgespielt          
h_start_button = uicontrol(hfig,...
                'style', 'pushbutton',...
                'units', 'normalized',...
                'position', [0.5, 0.85, 0.15, 0.05],...
                'FontUnits','normalized',...
                'Fontsize', 0.5,...
                'string', 'start audio',...
                'BackgroundColor', [background_user],...
                'callback', @start_audio);   
            
%--------------------------------------------------------------------------

% Mittels des Befehls 'buttondownfcn' werden die Funktionen azdir_change
% und eldir_change bei Klick in azi_panel, bzw. elev_panel ausgeführt
set(azi_panel, 'buttondownfcn', @azdir_change);
set(elev_panel, 'buttondownfcn', @eldir_change);

guidata(hfig, guihandles(hfig));


%--------------------Licence ---------------------------------------------
% Copyright (c) <2011-2013> F. Wichert, L. Hartog
% Institute for Hearing Technology and Audiology
% Jade University of Applied Sciences